import{S as v,a as u,i as l}from"./assets/vendor-CFAwn0qA.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const a={form:document.querySelector(".js-form"),loader:document.querySelector(".loader"),gallery:document.querySelector(".js-gallery"),loadmorebtn:document.querySelector(".loadmorebtn")};function h(){a.loader.classList.remove("is-hidden")}function p(){a.loader.classList.add("is-hidden")}function y(){a.gallery.innerHTML=""}function f(r){return r.map(({webformatURL:t,largeImageURL:s,tags:n,likes:e,views:o,comments:i,downloads:L})=>`
      <li>
        <a href="${s}">
          <img src="${t}" alt="${n}" loading="lazy" width="360" height="200"/>
        </a>
        <div>
          <p>likes: <span>${e}</span></p>
          <p>views: <span>${o}</span></p>
          <p>comments: <span>${i}</span></p>
          <p>downloads: <span>${L}</span></p>
        </div>
      </li>`).join("")}let m=null;function g(){m?m.refresh():m=new v(".js-gallery a")}u.defaults.baseURL="https://pixabay.com/api/";const b=(r,t,s)=>{const n={params:{key:"51390030-b864bce351d7615980478c23b",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:t}};return u.get("",n)},q=()=>{const r={params:{key:"51390030-b864bce351d7615980478c23b",q:"random",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:9}};return u.get("",r)};let c=1,d=9;const w=async()=>{try{const r=await q(""),t=f(r.data.hits);a.gallery.innerHTML=t,g()}catch{l.error({message:"что пошло не так"})}finally{p()}};w();const S=async r=>{try{r.preventDefault(),h(),c=1,y();const t=r.target.elements["search-text"].value.trim();if(t===""){l.info({message:"Введите поисковый запрос!"});return}const{data:s}=await b(t,c,d);if(!s.hits.length){l.error({message:"Нет результатов по вашему запросу"});return}const n=f(s.hits);a.gallery.innerHTML=n,g(),s.totalHits>d?a.loadmorebtn.classList.remove("is-hidden"):a.loadmorebtn.classList.add("is-hidden")}catch{l.error({message:"что пошло не так"}),y()}finally{p()}},x=async()=>{c+=1,h();try{const r=a.form.elements["search-text"].value.trim(),{data:t}=await b(r,c,d),s=f(t.hits);a.gallery.insertAdjacentHTML("beforeend",s),g(),t.totalHits<=c*d&&a.loadmorebtn.classList.add("is-hidden")}catch{l.error({message:"что пошло не так"})}finally{p()}};a.form.addEventListener("submit",S);a.loadmorebtn.addEventListener("click",x);
//# sourceMappingURL=index.js.map
